# Use the official OpenJDK image as the base image
FROM openjdk:8-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the application jar file to the container
COPY target/mads-video.jar /app/mads-video.jar

# Run the application when the container starts
CMD ["java", "-jar", "mads-video.jar"]
